### ISSUE TITLE
Undefined local variable or method `example` error

### ISSUE THREAD

**Issue by demisx** [zipmark/rspec_api_documentation#129]
Hi, 
I've followed the example and added this acceptance test:

``` ruby
# in spec/acceptance/syj_registrants_spec.rb
require 'spec_helper'
require 'rspec_api_documentation/dsl'

resource "SyjRegistrants" do
  get "/amg/syj/v1/regs?start=2013-03-01&end=2014-04-10" do
    example "Listing orders" do
      do_request

      status.should == 200
    end
  end
end
```

However, RSpec 3.0 returns the following error (see below). Am I missing something? Thx.

```
Failures:

  1) SyjRegistrants GET /amg/syj/v1/regs?start=2013-03-01&end=2014-04-10 Listing orders
     Failure/Error: do_request
     NameError:
       undefined local variable or method `example' for #<RSpec::ExampleGroups::SyjRegistrants::GETAmgSyjV1RegsStart20130301End20140410:0x007fafc303b0e0>
     # ./spec/acceptance/syj_registrants_spec.rb:7:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'
```
