### ISSUE TITLE
Empty Params on Post

### ISSUE THREAD

**Issue by k2heikkila** [zipmark/rspec_api_documentation#314]
Rails 5.0.0.1
Ruby 2.2.5
Rspec 3.5.0

I have tried every permutation I can think of to get params passed to my controller, but they are always empty. 

```
resource "DigitalAssets" do
  before do
    header "Accept", "application/json"
    header "Content-Type", "application/json"
  end

  post "api/v1/digital_assets" do
    with_options :scope => :digital_asset, :required => true do
      parameter asset_type: "Asset Type"
      parameter location: "Location"
      parameter client_id: "Client ID"
    end
    
    let(:asset_type) { "Website" }
    let(:location) { "acme.com"}
    let(:client_id) {1} 

    example "Create digital asset" do
      params.should eq({
        :digital_asset => {
          :asset_type => "Website",
          :location => "acme.com",
          :client_id => 1
        }
      })
      do_request
      expect(status).to be 201
    end
  end
end
```
And get 

```
Failure/Error:
      ...
      expected: {:digital_asset=>{:asset_type=>"Website", :location=>"acme.com", :client_id=>1}}
      got: {}
```
