### ISSUE TITLE
Feature request: I18n for parameters

### ISSUE THREAD

**Issue by arturtr** [zipmark/rspec_api_documentation#327]
In this case 
```ruby
    parameter :name, "Name of order", :required => true, :scope => :order
    parameter :paid, "If the order has been paid for", :required => true, :scope => :order
    parameter :email, "Email of user that placed the order", :scope => :order
```
more good to define parameter descriptions in localization files
```ruby
    parameter :name, :required => true, :scope => :order
    parameter :paid, :required => true, :scope => :order
    parameter :email, :scope => :order
```

```yaml
en:
  docs:
    order:
      name: "Name of order"
      paid: "If the order has been paid for"
      email: "Email of user that placed the order"
```

It will help to make specs more clear
